config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  resources :corsairs
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/corsair.rb
class Corsair < ApplicationRecord
  validates :first_name, length: {maximum: 20}
  validates :age, :inclusion =>{:in => (15..120)}
  validates :slack_handle, format: { without: /\s/ }
  validates :github_handle, format: { without: /\s/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/corsairs_controller.rb
class CorsairsController < ApplicationController
  
  def new
    @corsair = Corsair.new
  end

  def create
    @corsair = Corsair.new(corsair_params)
    if @corsair.save
      flash[:success] = "Congras, you've created your account"
      redirect_to @corsair
    else
      flash[:false] = "not success" 
      render 'new'
    end
  end

  def show
    @corsair = Corsair.find(params[:id])
  end

  def edit
    @corsair = Corsair.find(params[:id])
  end
 
  def update
    @corsair = Corsair.find(params[:id])
 
    if @corsair.update(corsair_params)
      flash[:success] = "Your account've updated!"
      redirect_to @corsair
    else
      flash[:false] = "not success"
      render 'edit'
    end
  end

  def destroy
  @corsair = Corsair.find(params[:id])

    if @corsair.destroy
      flash[:success] = "Your account've deleted!"
      redirect_to @corsair
    end
  end

  def index
    @corsairs = Corsair.all
  end

  private 
    def corsair_params
      params.require(:corsair).permit(:first_name, :age, :likeness, :bio, :slack_handle, :github_handle)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/corsairs_helper.rb
module CorsairsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/corsairs/edit.html.erb
<h1>Corsairs#edit</h1>
 
<%= form_for(@corsair) do |f| %>
 
  <p>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </p>
 
  <p>
    <%= f.label :age %>
    <%= f.text_area :age %>
  </p>
 
   <p>
    <%= f.label :bio %>
    <%= f.text_field :bio %>
  </p>

    <p>
    <%= f.label :slack_handle %>
    <%= f.text_field :slack_handle %>
  </p>

    <p>
    <%= f.label :github_handle %>
    <%= f.text_field :github_handle %>
  </p>

  <%= f.radio_button(:likeness, "kebab") %>
  <%= f.label(:kebab, "I like kebab") %>
  <%= f.radio_button(:likeness, "hummus") %>
  <%= f.label(:hummus, "I like hummus") %>

  <p>
    <%= f.submit "submit your change" %>
    <%= link_to 'Clique pour détruire', @corsair, method: :delete %>
  </p>
<% end %>

app/views/corsairs/index.html.erb
<h1>Index des Corsairs</h1>

<table>
  <tr>
    <th>first_name</th>
    <th>age</th>
    <th colspan="3"></th>
  </tr>

   <% @corsairs.each do |f| %>
    <tr>
      <td><%= f.first_name %></td>
      <td><%= f.age %></td>
      <td><%= link_to 'Show', corsair_path(f) %></td>   
    </tr>
  <% end %>
</table> 

app/views/corsairs/new.html.erb
<h1>Sign up please</h1>
<p>
  <%= form_for(@corsair) do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name, placeholder: "corsair1" %> 

    <%= f.label :age %>
    <%= f.text_field :age, placeholder: "33" %> 

    <%= f.submit "Submit your account", class: "btn btn-primary"%>
  <%end%>
</p>

app/views/corsairs/show.html.erb
<h1><%= @corsair.first_name %></h1>
<p><%= @corsair.age %></p>

<% if @corsair.slack_handle != nil %>
  <p>Voici le pseudo Slack de <%=@corsair.first_name%> : <%=@corsair.slack_handle%></p>
<% else %>
  <p><%=@corsair.first_name%> n'a pas encore renseigné son pseudo Slack !</p>
<% end %>

<p> <%= @corsair.first_name%> like <%= @corsair.likeness %></p>

<p><%= link_to "edit corsair", edit_corsair_path(@corsair) %> </p>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil",   root_path %></li>
        <li><%= link_to "Index des corsaires",   corsairs_path %></li>
        <li><%= link_to "Nouveau corsaire", new_corsair_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThpCorsaires</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Bienvenue !</h1>
  <h3>
    Ici, tu peux retrouver les corsaires 🎓
  </h3>
  <%= link_to "Enregistre-toi !", new_corsair_path, class: "btn btn-lg btn-primary" %>
</div>